name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
      - uses: actions/checkout@v4
      - run: go test

  build:
    name: Build and run CLI application
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
      - uses: actions/checkout@v4
      - run: go build
      - run: ./mediawiki-extension-downloader --help