# CC: https://github.com/thatisuday/tree/blob/master/.github/workflows/release.yml
name: release

on:
  release:
    types:
      - created

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Generate build files
        uses: thatisuday/go-build-action@v1
        with:
          platforms: "linux/amd64, linux/arm, linux/arm64"
          name: "mediawiki-extension-downloader"
          compress: "true"
          dest: "dist"
      - name: Upload build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*.tar.gz"